// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/app-info": {
            "get": {
                "description": "获取当前后端应用的版本、环境、运行状态等基础信息",
                "tags": [
                    "Base"
                ],
                "summary": "获取系统信息",
                "responses": {
                    "200": {
                        "description": "返回应用配置信息",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JsonResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.AppInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/article": {
            "get": {
                "description": "分页获取文章列表，包含分类名称和是否有更多",
                "tags": [
                    "Article"
                ],
                "summary": "获取文章列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页码 (默认1)",
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页条数 (默认10)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JsonResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.PageResult-model_ArticleVO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "description": "根据文章对象中的 ID 更新标题、内容、分类等信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Article"
                ],
                "summary": "更新文章",
                "parameters": [
                    {
                        "description": "需要更新的文章对象",
                        "name": "article",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Article"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功后的文章详情",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JsonResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.ArticleVO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "提交文章标题、内容等信息创建新篇章",
                "tags": [
                    "Article"
                ],
                "summary": "新增文章",
                "parameters": [
                    {
                        "description": "文章内容对象",
                        "name": "article",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Article"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回创建成功的文章详情",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JsonResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.ArticleVO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "根据文章 ID 永久删除文章",
                "tags": [
                    "Article"
                ],
                "summary": "删除文章",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "文章 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回被删除的文章 ID",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JsonResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/article/{id}": {
            "get": {
                "description": "根据文章 ID 查询文章的详细内容及分类信息",
                "tags": [
                    "Article"
                ],
                "summary": "获取文章详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "文章ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JsonResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.ArticleVO"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/mood": {
            "get": {
                "tags": [
                    "Mood"
                ],
                "summary": "获取心情列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页",
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页条数",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JsonResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.PageResult-model_Mood"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Mood"
                ],
                "summary": "修改心情",
                "parameters": [
                    {
                        "description": "心情对象",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Mood"
                        }
                    }
                ],
                "responses": {}
            },
            "post": {
                "tags": [
                    "Mood"
                ],
                "summary": "添加心情",
                "parameters": [
                    {
                        "description": "心情内容",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Mood"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/utils.JsonResult"
                        }
                    }
                }
            }
        },
        "/mood/{id}": {
            "delete": {
                "tags": [
                    "Mood"
                ],
                "summary": "删除心情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/type": {
            "get": {
                "description": "分页获取文章分类",
                "tags": [
                    "Type"
                ],
                "summary": "获取分类列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "当前页码 (默认1)",
                        "name": "current",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "每页条数 (默认10)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JsonResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.PageResult-model_Type"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "put": {
                "tags": [
                    "Type"
                ],
                "summary": "修改分类",
                "parameters": [
                    {
                        "description": "分类对象",
                        "name": "type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Type"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JsonResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Type"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "tags": [
                    "Type"
                ],
                "summary": "新增分类",
                "parameters": [
                    {
                        "description": "分类对象",
                        "name": "type",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Type"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JsonResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Type"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "Type"
                ],
                "summary": "删除分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JsonResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "integer"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/type/all": {
            "get": {
                "description": "通常用于前端下拉框",
                "tags": [
                    "Type"
                ],
                "summary": "获取全部分类",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JsonResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Type"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/type/{id}": {
            "get": {
                "tags": [
                    "Type"
                ],
                "summary": "获取分类详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/utils.JsonResult"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Type"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "datatypes.JSONType-model_AppContent": {
            "type": "object"
        },
        "model.AppInfo": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "使用泛型 JSONType 绑定，实现自动序列化/反序列化",
                    "allOf": [
                        {
                            "$ref": "#/definitions/datatypes.JSONType-model_AppContent"
                        }
                    ]
                },
                "id": {
                    "type": "integer"
                },
                "version": {
                    "type": "string",
                    "example": "0.1"
                }
            }
        },
        "model.Article": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "description": "必须大写开头！后面反引号里的才是数据库真实的列名",
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "typeId": {
                    "type": "string"
                }
            }
        },
        "model.ArticleVO": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "description": "必须大写开头！后面反引号里的才是数据库真实的列名",
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "typeId": {
                    "type": "string"
                },
                "typeName": {
                    "description": "扩展字段",
                    "type": "string"
                }
            }
        },
        "model.Mood": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createTime": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "model.PageResult-model_ArticleVO": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "hasMore": {
                    "description": "是否有更多",
                    "type": "boolean"
                },
                "list": {
                    "description": "数据列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ArticleVO"
                    }
                },
                "size": {
                    "description": "每页条数",
                    "type": "integer"
                },
                "total": {
                    "description": "总条数",
                    "type": "integer"
                }
            }
        },
        "model.PageResult-model_Mood": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "hasMore": {
                    "description": "是否有更多",
                    "type": "boolean"
                },
                "list": {
                    "description": "数据列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Mood"
                    }
                },
                "size": {
                    "description": "每页条数",
                    "type": "integer"
                },
                "total": {
                    "description": "总条数",
                    "type": "integer"
                }
            }
        },
        "model.PageResult-model_Type": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "当前页码",
                    "type": "integer"
                },
                "hasMore": {
                    "description": "是否有更多",
                    "type": "boolean"
                },
                "list": {
                    "description": "数据列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Type"
                    }
                },
                "size": {
                    "description": "每页条数",
                    "type": "integer"
                },
                "total": {
                    "description": "总条数",
                    "type": "integer"
                }
            }
        },
        "model.Type": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "utils.JsonResult": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "业务约定：0 为成功，-1 为失败",
                    "type": "integer"
                },
                "data": {
                    "description": "业务数据"
                },
                "msg": {
                    "description": "错误描述或提示信息",
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "基础模块",
            "name": "Base"
        },
        {
            "description": "文章模块",
            "name": "Article"
        },
        {
            "description": "心情模块",
            "name": "Mood"
        },
        {
            "description": "博客类型模块",
            "name": "Type"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "我的博客 API",
	Description:      "基于 Go + GORM 的博客系统后端",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
