basePath: /api
definitions:
  datatypes.JSONType-model_AppContent:
    type: object
  model.AppInfo:
    properties:
      content:
        allOf:
        - $ref: '#/definitions/datatypes.JSONType-model_AppContent'
        description: 使用泛型 JSONType 绑定，实现自动序列化/反序列化
      id:
        type: integer
      version:
        example: "0.1"
        type: string
    type: object
  model.Article:
    properties:
      content:
        type: string
      createTime:
        type: string
      description:
        type: string
      id:
        description: 必须大写开头！后面反引号里的才是数据库真实的列名
        type: integer
      title:
        type: string
      typeId:
        type: string
    type: object
  model.ArticleVO:
    properties:
      content:
        type: string
      createTime:
        type: string
      description:
        type: string
      id:
        description: 必须大写开头！后面反引号里的才是数据库真实的列名
        type: integer
      title:
        type: string
      typeId:
        type: string
      typeName:
        description: 扩展字段
        type: string
    type: object
  utils.JsonResult:
    properties:
      code:
        description: 业务约定：0 为成功，-1 为失败
        type: integer
      data:
        description: 业务数据
      msg:
        description: 错误描述或提示信息
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: 基于 Go + GORM 的博客系统后端
  title: 我的博客 API
  version: "0.1"
paths:
  /app-info:
    get:
      description: 获取当前后端应用的版本、环境、运行状态等基础信息
      responses:
        "200":
          description: 返回应用配置信息
          schema:
            allOf:
            - $ref: '#/definitions/utils.JsonResult'
            - properties:
                data:
                  $ref: '#/definitions/model.AppInfo'
              type: object
      summary: 获取系统信息
      tags:
      - Base
  /article:
    delete:
      description: 根据文章 ID 永久删除文章
      parameters:
      - description: 文章 ID
        in: query
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: 返回被删除的文章 ID
          schema:
            allOf:
            - $ref: '#/definitions/utils.JsonResult'
            - properties:
                data:
                  type: integer
              type: object
      summary: 删除文章
      tags:
      - Article
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/utils.JsonResult'
      summary: 获取文章列表
      tags:
      - Article
    post:
      description: 提交文章标题、内容等信息创建新篇章
      parameters:
      - description: 文章内容对象
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.Article'
      responses:
        "200":
          description: 返回创建成功的文章详情
          schema:
            allOf:
            - $ref: '#/definitions/utils.JsonResult'
            - properties:
                data:
                  $ref: '#/definitions/model.ArticleVO'
              type: object
      summary: 新增文章
      tags:
      - Article
    put:
      consumes:
      - application/json
      description: 根据文章对象中的 ID 更新标题、内容、分类等信息
      parameters:
      - description: 需要更新的文章对象
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/model.Article'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功后的文章详情
          schema:
            allOf:
            - $ref: '#/definitions/utils.JsonResult'
            - properties:
                data:
                  $ref: '#/definitions/model.ArticleVO'
              type: object
      summary: 更新文章
      tags:
      - Article
  /article/{id}:
    get:
      description: 根据文章 ID 查询文章的详细内容及分类信息
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/utils.JsonResult'
            - properties:
                data:
                  $ref: '#/definitions/model.ArticleVO'
              type: object
      summary: 获取文章详情
      tags:
      - Article
swagger: "2.0"
tags:
- description: 基础模块
  name: Base
- description: 文章模块
  name: Article
